config/routes.rb
POS::Application.routes.draw do
  

  get "home/index"

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
  

  root :to=>"home#index"
    
  resources :transactions, :customers, :products, :home

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  load_and_authorize_resource
  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    @transaction = Transaction.find(params[:id])
    authorize! :read, @transactions 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.json
  def new
    @transaction = Transaction.new

    @customer = Customer.new
    @transaction.customer_id = @customer.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit

    @transaction = Transaction.find(params[:id])

  end

  # POST /transactions
  # POST /transactions.json
  def create
    customer_id = params[:transaction].delete(:customer_id)
    product_id = params[:transaction].delete(:product_id)
    @transaction = Transaction.new(params[:transaction])
    @transaction.customer_id = customer_id
    @transaction.product_id = product_id


    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render json: @transaction, status: :created, location: @transaction }
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.json
  def update
    customer_id = params[:transaction].delete(:customer_id)
    product_id = params[:transaction].delete(:product_id)
    @transaction = Transaction.find(params[:id])
    @transaction.customer_id = customer_id
    @transaction.product_id = product_id

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br />
    <%= f.select :customer_id,  Customer.all.collect { |c| [c.name, c.id] }, :prompt => 'Select a Customer'%><br />
    <%= f.label :product_id %><br />
    <%= f.select :product_id,  Product.all.collect { |c| [c.name, c.id] }, :prompt => 'Select a Product'%><br />
    <%= f.label :transaction_date %><br />
    <%= f.date_select :transaction_date, :start_year => 1950, :end_year => 2012 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Listing transactions</h1>

<table>
  <tr>
    <th>Customer</th>
    <th>Product</th>
    <th>Transaction date</th>
    <th></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td><%= transaction.customer_id %></td>
    <td><%= transaction.product_id %></td>
    <td><%= transaction.transaction_date %></td>
    <td><%= link_to 'Show', transaction %></td>
<% if can? :update, @transaction %>    
    <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
    <td><%= link_to 'Destroy', transaction, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>  
<% end %>

</table>

<br />

<%= link_to 'New Transaction', new_transaction_path %> |
<%= link_to 'Back to Home', home_index_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>


<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Transaction date:</b>
  <%= @transaction.transaction_date %>
</p>
<p>
  <b>Customer:</b>
  <%= @transaction.customer_id %>
</p>
<p>
  <b>Product:</b>
  <%= @transaction.product_id %>
</p>

<% if can? :update, @transaction %>
<%= link_to 'Edit', edit_transaction_path(@transaction) %>
<%end%> |
<%= link_to 'Back', transactions_path %>